groups:
  - name: itglue_mcp_alerts
    interval: 30s
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.service }} is down"
          description: "{{ $labels.service }} has been down for more than 2 minutes."

      # API response time alerts
      - alert: HighAPIResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API response time"
          description: "95th percentile response time is above 2 seconds (current: {{ $value }}s)"

      - alert: CriticalAPIResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical API response time"
          description: "95th percentile response time is above 5 seconds (current: {{ $value }}s)"

      # Error rate alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% (current: {{ $value | humanizePercentage }})"

      # Database alerts
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute"

      - alert: PostgreSQLHighConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL high connection usage"
          description: "PostgreSQL connection usage is above 80% (current: {{ $value | humanizePercentage }})"

      - alert: PostgreSQLSlowQueries
        expr: rate(pg_stat_statements_mean_exec_time_seconds[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL slow queries detected"
          description: "Average query execution time is above 1 second"

      # Redis alerts
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 1 minute"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is above 90% (current: {{ $value | humanizePercentage }})"

      # Neo4j alerts
      - alert: Neo4jDown
        expr: neo4j_database_system_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Neo4j is down"
          description: "Neo4j database has been down for more than 1 minute"

      # Qdrant alerts
      - alert: QdrantDown
        expr: up{job="qdrant"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Qdrant is down"
          description: "Qdrant vector database has been down for more than 1 minute"

      # Celery alerts
      - alert: CeleryWorkerDown
        expr: celery_workers_count == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "No Celery workers available"
          description: "No Celery workers have been available for more than 2 minutes"

      - alert: CeleryHighQueueSize
        expr: celery_queue_length > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Celery queue backlog"
          description: "Celery queue has more than 1000 pending tasks (current: {{ $value }})"

      - alert: CeleryTaskFailureRate
        expr: rate(celery_task_failed_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Celery task failure rate"
          description: "Celery task failure rate is above 10% (current: {{ $value | humanizePercentage }})"

      # System resource alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% (current: {{ $value }}%)"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90% (current: {{ $value }}%)"

      - alert: DiskSpaceWarning
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 20% (current: {{ $value }}%)"

      # IT Glue sync alerts
      - alert: SyncJobFailed
        expr: increase(itglue_sync_failures_total[1h]) > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "IT Glue sync failures"
          description: "More than 3 sync failures in the last hour"

      - alert: SyncJobDelayed
        expr: time() - itglue_last_sync_timestamp > 86400
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "IT Glue sync delayed"
          description: "Last successful sync was more than 24 hours ago"

      # Rate limiting alerts
      - alert: ITGlueRateLimitApproaching
        expr: itglue_rate_limit_remaining / itglue_rate_limit_max < 0.2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "IT Glue API rate limit approaching"
          description: "Less than 20% of rate limit remaining ({{ $value }} requests left)"