[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 10
headless = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = true

[client]
showErrorDetails = true
toolbarMode = "minimal"